-define (WEDDING_STATE_REGISTERED, 0).
-define (WEDDING_STATE_CEREMONY, 1).
-define (WEDDING_STATE_CRUISE, 2).

-define (WEDDING_CEREMONY_NOTIFY, 0).
-define (WEDDING_CEREMONY_START, 1).
-define (WEDDING_CEREMONY_END, 2).

-define (WEDDING_CEREMONY_NOTIFY_DURATION, 5 * 60).

-define (WEDDING_INTIMACY_BY_GROUP, 1).
-define (WEDDING_INTIMACY_BY_FLOWER, 2).
-define (WEDDING_INTIMACY_BY_INSTANCE, 3).