-define(ACUTION_ITEMS_MAXNUM,8).
-define(ACUTION_SERCH_TYPE_ALL,0).
-define(ACUTION_SERCH_TYPE_ITEMNAME,1).

-define(ACUTION_MAX_LOG_NUM,10).

-define(ACUTION_SERCH_RECORD_NUM,20).
-define(ACUTION_SERCH_ITEM_RECORD_NUM,12).

-define(ACUTION_OVERDUA_CHECK_DURATION,600000).

-define(ACUTION_OVERDUA_TIME,86400000).

-define(REBACK_ITEM_NUM_ONCE_MAIL,3).