-record(banquet_option,{banquet_id,instance_proto,looptime,duration,dancing,cheering,pet_swanking,vip_exp_addition,vip_op_addition}).
-record(banquet_exp,{level,exp,soulpower,dancing_self,dancing_be,cheering_self,cheering_be,pet_swanking}).
